/* eslint-disable react/no-unescaped-entities */
import Editor from "@monaco-editor/react";
import type {
  GetStaticPaths,
  GetStaticProps,
  InferGetStaticPropsType,
  NextPage,
} from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

const C = ({ className, ...props }: React.HTMLProps<HTMLSpanElement>) => (
  <code className={`p-1 bg-gray-100 rounded-md ${className}`} {...props} />
);

const sections: Record<string, any> = {
  first: {
    title: "Section 1",
    nextSection: "second",
    initialCode: "balls.map()",
    data: [
      { name: "baseball", size: 1 },
      { name: "basketball", size: 3 },
      { name: "tennisball", size: 1 },
      { name: "volleyball", size: 2 },
      { name: "football", size: 2 },
    ],
    expected: [
      "baseball",
      "basketball",
      "tennisball",
      "volleyball",
      "football",
    ],
  },
  second: {
    title: "Section 2",
    nextSection: "third",
    initialCode: "balls.filter()",
    data: [
      { name: "baseball", size: 1 },
      { name: "basketball", size: 3 },
      { name: "tennisball", size: 1 },
      { name: "volleyball", size: 2 },
      { name: "football", size: 2 },
    ],
    expected: [
      { name: "basketball", size: 3 },
      { name: "volleyball", size: 2 },
      { name: "football", size: 2 },
    ],
  },
};

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    fallback: false,
    paths: [
      { params: { section: "first" } },
      { params: { section: "second" } },
    ],
  };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const section = context.params?.section;
  if (
    section == null ||
    typeof section !== "string" ||
    sections[section] == null
  )
    return { props: sections.first };
  return { props: sections[section] };
};

const Home: NextPage = (
  props: InferGetStaticPropsType<typeof getStaticProps>
) => {
  const { nextSection, data, expected, title, initialCode } = props;
  const [code, setCode] = useState<string>(initialCode);
  const [result, setResult] = useState<string | null>(null);

  const matches =
    result == null ? null : JSON.stringify(expected) === JSON.stringify(result);

  return (
    <div className="flex items-center flex-col container mx-auto">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-12 px-12 lg:px-36 w-full flex flex-col">
        <h1 className="text-2xl font-bold mb-1">{title}</h1>

        <p className="text-sm text-gray-500 mb-4 ">
          In the first section you will learn how to master <C>map</C>
        </p>

        <p className="text-gray-800 ">
          First give the name of every ball in an array
        </p>

        <Editor
          className="mt-8"
          height="40vh"
          defaultLanguage="javascript"
          value={code}
          onChange={(nextCode) => setCode(nextCode ?? "")}
          theme="vs-dark"
        />

        <button
          type="button"
          className="cursor-pointer my-2 py-1 bg-green-400 rounded-lg self-start px-4"
          onClick={() => {
            const codeToExecute = [
              `const balls = JSON.parse('${JSON.stringify(data)}');`,
              code,
            ].join("\n");

            console.log(codeToExecute);
            const nextResult = eval(codeToExecute);
            setResult(nextResult);
          }}
        >
          Run
        </button>

        <h3 className="mt-4 text-xl font-semibold">Result</h3>
        <C className="mt-2 text-sm self-start">{JSON.stringify(result)}</C>

        <h3 className="mt-4 text-xl font-semibold">Expected</h3>
        <C className="mt-2 text-sm self-start">{JSON.stringify(expected)}</C>

        {matches === true ? (
          <div className="flex flex-col mt-8">
            <h3 className="text-2xl mt-2 font-bold">Nice Job ✅</h3>
            <Link href={nextSection}>
              <a className="cursor-pointer mt-2 py-2 bg-blue-600 text-white shadow-lg rounded-lg self-start px-4">
                Next Section
              </a>
            </Link>
          </div>
        ) : matches === false ? (
          <div className="flex flex-col mt-8">
            <h3 className="text-2xl mt-2 font-bold">Results differ 🧐</h3>
            <Link href={nextSection}>
              <a className="text-sm cursor-pointer self-start">Skip Section</a>
            </Link>
          </div>
        ) : null}
      </main>
    </div>
  );
};

export default Home;
