import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const C = ({ className, ...props }: React.HTMLProps<HTMLSpanElement>) => (
  <code className={`p-1 bg-gray-100 rounded-md ${className}`} {...props} />
);

const Home: NextPage = () => {
  return (
    <div className="flex items-center flex-col container mx-auto">
      <Head>
        <title>JS Collections Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-12 lg:p-36">
        <h1 className="text-3xl font-bold mb-8">
          Welcome to the Javascript Collections Tutorial
        </h1>

        <p className="text-gray-800 mb-4">
          I think everyone should be able to understand the methods Javascripts
          gives us, to <C>filter</C>, <C>map</C> and <C>reduce</C> arrays and
          objects as well!
        </p>

        <Link href="tutorial">
          <a className="px-4 py-2 bg-blue-600 rounded-md text-white shadow-lg cursor-pointer font-semibold">
            Start Tutorial
          </a>
        </Link>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by buschco
        </a>
      </footer>
    </div>
  );
};

export default Home;
